# Generated by Django 3.1.7 on 2021-03-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('pass_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('pass_name', models.CharField(default='pass', max_length=50)),
                ('pass_email', models.EmailField(default='pass@pass.pass', max_length=254, unique=True)),
                ('pass_pass', models.CharField(default='pass', max_length=50)),
                ('pass_address', models.TextField(default='123,pass,pass,pass,123', max_length=200)),
                ('pass_contact', models.CharField(default='0123456789', max_length=10)),
            ],
        ),
    ]
