# Generated by Django 3.1.7 on 2021-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='pass_pass',
            field=models.CharField(default='pass_pass', max_length=50),
        ),
    ]
