# Generated by Django 3.1.7 on 2021-03-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210310_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='pass_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pass_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pass_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='pass_pass',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Book_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('travel_source', models.CharField(max_length=50)),
                ('travel_destination', models.CharField(max_length=50)),
                ('seat_pre', models.CharField(max_length=10)),
                ('seat_meal', models.CharField(max_length=10)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user_data')),
            ],
        ),
    ]
