# Generated by Django 3.1.7 on 2021-03-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210310_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_data',
            name='user_data',
        ),
    ]
