# Generated by Django 3.1.7 on 2021-03-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_book_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Data',
            fields=[
                ('travel_pnr', models.CharField(max_length=12, unique=True)),
                ('pass_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('travel_date', models.DateField()),
                ('travel_source', models.CharField(max_length=50)),
                ('travel_destination', models.CharField(max_length=50)),
                ('seat_pre', models.CharField(max_length=10)),
                ('seat_meal', models.CharField(max_length=10)),
            ],
        ),
    ]
