# Generated by Django 3.1.7 on 2021-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_book_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_data',
            name='pass_email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
