# Generated by Django 3.1.7 on 2021-03-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210310_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Data',
        ),
    ]
