# Generated by Django 3.1.7 on 2021-03-10 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_book_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Data',
        ),
    ]
